org: henryqs36
service: api-comentario

provider:
  name: aws
  runtime: python3.12
  # Default memory size for functions (default: 1024MB)
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::708642711016:role/LabRole	
  environment:
    TABLE_NAME: ${sls:stage}-t_comentarios
    BUCKET_NAME: ${sls:stage}-bucket-ingesta-comentarios

functions:
  crear:
    handler: comentario.lambda_handler
    events:
      - http:
          path: /comentario/crear
          method: post
          cors: true
          integration: lambda

resources:
  Resources:
    TablaComentarios:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: uuid
            KeyType: RANGE
        # Set the capacity to auto-scale
        BillingMode: PAY_PER_REQUEST
    BucketComentarios:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET_NAME}
        OwnershipControls:
          Rules:
            - ObjectOwnership: BucketOwnerPreferred

        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          IgnorePublicAcls: false
          BlockPublicPolicy: false
          RestrictPublicBuckets: false
        BucketPolicy:
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: "PublicReadGetObject"
                Effect: "Allow"          
                Principal: "*"          
                Action: "s3:GetObject"  
                Resource: "arn:aws:s3:::${self:provider.environment.BUCKET_NAME}/*" 
